name: Mirror to inkioweb

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to destination repository
        env:
          DEST_TOKEN: ${{ secrets.SYNC_TOKEN }}
          DEST_REPO: "github.com/inkioweb/inkio-web-agency.git"
        run: |
          git remote add mirror https://inkioweb:$DEST_TOKEN@$DEST_REPO
          git push mirror main --force --tags
